kind: Namespace
apiVersion: v1
metadata:
  name: argocd
  labels:
    kubernetes.io/metadata.name: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-1"
